### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by MuruganR96** [jaraco/inflect#119]
when importing inflect, i am getting invalid syntax

```
Traceback (most recent call last):
  File "inference.py", line 28, in <module>
    from tacotron2.text import text_to_sequence
  File "/root/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/text/__init__.py", line 3, in <module>
    from tacotron2.text import cleaners
  File "/root/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/text/cleaners.py", line 17, in <module>
    from .numbers import normalize_numbers
  File "/root/DeepLearningExamples/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/text/numbers.py", line 3, in <module>
    import inflect
  File "/usr/local/lib/python3.5/dist-packages/inflect.py", line 1455
    pl_sb_postfix_adj: Dict[str, str] = {}
                     ^
SyntaxError: invalid syntax

```
How to resolve this issue? anyone help me.

**Comment by jaraco** [comment]
It appears you're using Python 3.5. Inflect dropped support for Python 3.5 in the [4.0 release](https://inflect.readthedocs.io/en/latest/history.html#v4-0-0). You'll need to install with pip 9.x or later or install `inflect<4` to run on Python 3.5.
