### ISSUE TITLE
query of death

### ISSUE THREAD

**Issue by uriva** [jaraco/inflect#68]
On version 2.1.0
This string:
"lens with a lens ()."
yields an exception.

```
> /lib/python3.6/site-packages/inflect.py in plural(self, text, count)
>    2239             self._pl_special_adjective(word, count)
>    2240             or self._pl_special_verb(word, count)
> -> 2241             or self._plnoun(word, count),
>    2242         )
>    2243         return "{}{}{}".format(pre, plural, post)
> 
> /lib/python3.6/site-packages/inflect.py in postprocess(self, orig, inflected)
>    2209                 continue
>    2210             if word.capitalize() == word:
> -> 2211                 result[index] = result[index].capitalize()
>    2212             if word == word.upper():
>    2213                 result[index] = result[index].upper()
```

IndexError: list index out of range

**Comment by hugovk** [comment]
Please could you share a minimal code example of how you called inflect?

**Comment by uriva** [comment]
```
import inflect
inflect.engine().plural_noun("lens with a lens ().")
```

**Comment by hugovk** [comment]
I can reproduce with Inflect 2.1.0 but not 1.0.1.

---

`git bisect` says ff5592bb298206d457e432822bdf119fc2a5bced is the first bad commit
Date:   Tue Sep 25 18:22:07 2018 +0200
"Fix more capitalization errors"

---

```
⌂132% [hugo:~/github/inflect] ff5592b* 1m25s ± cat 1.sh
pip install -e .
python 1.py
⌂101% [hugo:~/github/inflect] ff5592b* ± cat 1.py
import inflect
inflect.engine().plural_noun("lens with a lens ().")
```


```
⌂106% [hugo:~/github/inflect] master* ± git bisect good v1.0.1
You need to start by "git bisect start"
Do you want me to do it for you [Y/n]? y
⌂111% [hugo:~/github/inflect] master* ± git bisect bad v2.1.0
Bisecting: 36 revisions left to test after this (roughly 5 steps)
[70a00b233211f4d7ec0ce7b76cd3c78280d9395c] Return boolean value directly
⌂108% [hugo:~/github/inflect] 70a00b2* ± git bisect run sh 1.sh
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 1.0.1
    Uninstalling inflect-1.0.1:
      Successfully uninstalled inflect-1.0.1
  Running setup.py develop for inflect
Successfully installed inflect
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    inflect.engine().plural_noun("lens with a lens ().")
  File "/Users/hugo/github/inflect/inflect.py", line 1572, in plural_noun
    plural = self.postprocess(word, self._plnoun(word, count))
  File "/Users/hugo/github/inflect/inflect.py", line 1490, in postprocess
    result[index] = result[index].capitalize()
IndexError: list index out of range
Bisecting: 18 revisions left to test after this (roughly 4 steps)
[9ec7eb5049409022f278b84fc7f59f9651f5e9b2] Merge branch 'master' into inflect_ast
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 2.0.0
    Uninstalling inflect-2.0.0:
      Successfully uninstalled inflect-2.0.0
  Running setup.py develop for inflect
Successfully installed inflect
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[8d7944018a59a05399a93ed74f1213f9e78358c9] Merge pull request #56 from nielstron/units-plural
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 1.0.1
    Uninstalling inflect-1.0.1:
      Successfully uninstalled inflect-1.0.1
  Running setup.py develop for inflect
Successfully installed inflect
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    inflect.engine().plural_noun("lens with a lens ().")
  File "/Users/hugo/github/inflect/inflect.py", line 1623, in plural_noun
    plural = self.postprocess(word, self._plnoun(word, count))
  File "/Users/hugo/github/inflect/inflect.py", line 1541, in postprocess
    result[index] = result[index].capitalize()
IndexError: list index out of range
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[dd01c0b3409d041ffc0819460f3328ff4aed9a48] Refine degree handling
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 1.0.1
    Uninstalling inflect-1.0.1:
      Successfully uninstalled inflect-1.0.1
  Running setup.py develop for inflect
Successfully installed inflect
Bisecting: 2 revisions left to test after this (roughly 1 step)
[b29181813045f3062209cbff9760ce1747c2c164] Include test for fixed issue #5 (was already fixed before)
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 1.0.1
    Uninstalling inflect-1.0.1:
      Successfully uninstalled inflect-1.0.1
  Running setup.py develop for inflect
Successfully installed inflect
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    inflect.engine().plural_noun("lens with a lens ().")
  File "/Users/hugo/github/inflect/inflect.py", line 1620, in plural_noun
    plural = self.postprocess(word, self._plnoun(word, count))
  File "/Users/hugo/github/inflect/inflect.py", line 1538, in postprocess
    result[index] = result[index].capitalize()
IndexError: list index out of range
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[ff5592bb298206d457e432822bdf119fc2a5bced] Fix more capitalization errors
running sh 1.sh
Obtaining file:///Users/hugo/github/inflect
  Installing build dependencies ... done
Installing collected packages: inflect
  Found existing installation: inflect 1.0.1
    Uninstalling inflect-1.0.1:
      Successfully uninstalled inflect-1.0.1
  Running setup.py develop for inflect
Successfully installed inflect
Traceback (most recent call last):
  File "1.py", line 2, in <module>
    inflect.engine().plural_noun("lens with a lens ().")
  File "/Users/hugo/github/inflect/inflect.py", line 1620, in plural_noun
    plural = self.postprocess(word, self._plnoun(word, count))
  File "/Users/hugo/github/inflect/inflect.py", line 1538, in postprocess
    result[index] = result[index].capitalize()
IndexError: list index out of range
ff5592bb298206d457e432822bdf119fc2a5bced is the first bad commit
commit ff5592bb298206d457e432822bdf119fc2a5bced
Date:   Tue Sep 25 18:22:07 2018 +0200

    Fix more capitalization errors

:100644 100644 e124f2723776835da46bd986b8c56d3a8806b149 da593566f3382121dfcd6af5e16cd023e3a40650 M	inflect.py
bisect run success
```

**Comment by uriva** [comment]
@nielstron in case you have a quick fix

**Comment by hugovk** [comment]
Although, junk-in-junk-out, "lens with a lens ()." clearly isn't a noun or pronoun, so I wouldn't expect anything sensible out:

> ``plural_noun(word, count=None)``
>
> The method ``plural_noun()`` takes a *singular* English noun or
 pronoun and returns its plural. Pronouns in the nominative ("I" ->
 "we") and accusative ("me" -> "us") cases are handled, as are
 possessive pronouns ("mine" -> "ours").


https://github.com/jazzband/inflect/blob/master/README.rst#inflecting-plurals-and-singulars

**Comment by uriva** [comment]
Ok but I don't think the user should validate for noun-ness at the price of an exception.
If there are constraints such as (e.g. no spaces or special characters) they should be clearly stated. Especially if this behaviour changed from previous versions.

**Comment by nielstron** [comment]
The problem here is that the input is not even purely words. for "a lens for a lens", no exception will be thrown.

A quick fix would obviously be checking if either accessed array is long enough or simply catching the exception and return the result until it was thrown (the garbage is returned but this is only the case for garbage)

**Comment by uriva** [comment]
#69

**Comment by jaraco** [comment]
This issue is no longer reproducible:

```
>>> import inflect
>>> eng = inflect.engine()
>>> eng.plural('lens with a lens().')
'lenses with lens().s'
```
